version: '3'

services:
  db:
    container_name: postgres12
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
