version: '3'

# need to create network first: docker network create bank-network
networks:
    bank-network:
        external: true

services:
  db:
    container_name: postgres12
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    networks: # attach this container to this network
      - bank-network
